#!/bin/sh
# --------------------------------------------------------------------------------
# syntax : gman <interface> [<new interface>]
# sample : gman mon0 wlan0
# --------------------------------------------------------------------------------
if [ -z "$1" ]; then
	echo "syntax : gman <interface> [<new interface>]"
	echo "sample : gman mon0 wlan0"
	exit 1
fi

INTERFACE="$1"
NEW_INTERFACE="$1"
if [ ! -z "$2" ]; then
	NEW_INTERFACE="$2"
fi

echo sudo ifconfig $INTERFACE down; sudo ifconfig $INTERFACE down
if [ ! -z "$2" ]; then
	echo sudo ip link set $INTERFACE name $NEW_INTERFACE; sudo ip link set $INTERFACE name $NEW_INTERFACE
	echo sudo ifconfig $NEW_INTERFACE down; sudo ifconfig $NEW_INTERFACE down
	echo sleep 1; sleep 1
fi
echo sudo iwconfig $NEW_INTERFACE mode managed; sudo iwconfig $NEW_INTERFACE mode managed
echo sudo ifconfig $NEW_INTERFACE up; sudo ifconfig $NEW_INTERFACE up
